import { HiOutlineMail } from 'react-icons/hi';
import { FaGithub, FaTumblr } from 'react-icons/fa';

import {
    FaJava
} from 'react-icons/fa';

import {
    SiReact,
    SiTailwindcss,
    SiSpring,
    SiSpringboot,
    SiAmazonwebservices,
    SiPostgresql,
    SiMysql,
    SiDocker,
    SiKubernetes,
    SiPython,
    SiJavascript,
    SiTypescript,
    SiRedis,
    SiGithub,
    SiGitlab,
    SiNotion,
    SiDiscord,
    SiFigma,
    SiMariadb,
    SiGithubactions,
    SiArgo,
    SiJenkins,
    SiVuedotjs,
    SiAmazonec2,
    SiAmazons3,
    SiAmazonroute53,
    SiVercel,
    SiRender,
    SiGunicorn,
    SiFlask,
} from 'react-icons/si';

export const techIcons = {
    React: SiReact,
    'Tailwind CSS': SiTailwindcss,
    PostgreSQL: SiPostgresql,
    Spring: SiSpring,
    'Spring Boot': SiSpringboot,
    AWS: SiAmazonwebservices,
    MySQL: SiMysql,
    Docker: SiDocker,
    Kubernetes: SiKubernetes,
    Java: FaJava,
    Python: SiPython,
    JavaScript: SiJavascript,
    TypeScript: SiTypescript,
    Redis: SiRedis,
    Github: SiGithub,
    GitLab: SiGitlab,
    Notion: SiNotion,
    Discord: SiDiscord,
    Figma: SiFigma,
    Mariadb: SiMariadb,
    GithubActions: SiGithubactions,
    Argo: SiArgo,
    Jenkins: SiJenkins,
    Vuejs: SiVuedotjs,
    EC2: SiAmazonec2,
    S3: SiAmazons3,
    Route53: SiAmazonroute53,
    Vercel: SiVercel,
    Render: SiRender,
    Flask: SiFlask,
    Gunicorn: SiGunicorn,
};

export const contactIcons = {
    email: HiOutlineMail,
    github: FaGithub,
    tistory: FaTumblr,
};

export const brandColors = {
    React: '#61DAFB',
    Vuejs: '#42B883',
    'Tailwind CSS': '#38BDF8',
    PostgreSQL: '#336791',
    MySQL: '#4479A1',
    Mariadb: '#003545',
    Spring: '#6DB33F',
    'Spring Boot': '#6DB33F',
    AWS: '#FF9900',
    EC2: '#FF9900',
    S3: '#569A31',
    Route53: '#8C4FFF',
    Docker: '#2496ED',
    Kubernetes: '#326CE5',
    Java: '#007396',
    Python: '#3776AB',
    JavaScript: '#F7DF1E',
    TypeScript: '#3178C6',
    Redis: '#DC382D',
    Github: '#181717',
    GitLab: '#FC6D26',
    Notion: '#000000',
    Discord: '#5865F2',
    Figma: '#F24E1E',
    GithubActions: '#2088FF',
    Argo: '#EF7B4D',
    Jenkins: '#D24939',
    Vercel: '#000000',
    Render: '#46E3B7',
};